# Macro file for the initialization of example B1
# when running in interactive mode without visualization
#
# Set some default verbose
/control/verbose 2
/control/saveHistory
/run/verbose 2

/random/setSeeds 1234515 9816459
#
# Change the default number of threads (in multi-threaded mode)
/run/numberOfThreads 4
#
# Initialize kernel
/lumi/det/setGDML ../geometry/lumi_P2.gdml
/run/initialize
/lumi/gun/beamtype 0
